In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset.columns
dataset = pd.get_dummies(dataset , dtype = int,  drop_first=True)

In [7]:
independence = dataset[['age','bmi', 'children','sex_male', 'smoker_yes']]
dependence = dataset[['charges']]

In [8]:
dependence

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independence, dependence, test_size = 0.30, random_state = 0)

In [99]:
from sklearn.svm import SVR
regressor=SVR(kernel = "linear",C=3000)
regressor=regressor.fit(X_train,y_train)

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [100]:
y_pred=regressor.predict(X_test)

In [101]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)
r_score

0.7590890367741108

In [102]:
import pickle 
filename = "final_modal_svm.sav"

In [103]:
pickle.dump(regressor,open(filename,'wb'))

In [105]:
loaded_model = pickle.load(open("final_modal_svm.sav",'rb'))
result = loaded_model.predict([[20 , 27.978 , 0 , 1 , 0]])

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(

In [106]:
result

array([1288.59435763])